name = "analytics-api"
main = "src/worker.js"
compatibility_date = "2024-08-06"

[[r2_buckets]]
binding = "analytics_data"
bucket_name = "analytics-data"

[[kv_namespaces]]
binding = "ANALYTICS_KV"
id = "2c6d5729ab6649d5b8d4da134c761317"
preview_id = "f37f9d7d47244545b51afe1e0cd6069f"

# Route configuration for custom domain - using path instead of subdomain
[[routes]]
pattern = "analytics.ujjwalvivek.com/api*"
zone_name = "ujjwalvivek.com"
